default_platform(:android)

platform :android do
  lane :build_apk do
    gradle(
      task: "assemble",
      build_type: 'Debug'
    )
  end

  lane :run_test do | params |
      if params == "Both"
        unit_tests
        ui_tests
      end
      if params == "UI Test"
        ui_tests
      end
      if params == "Unit Test"
        unit_tests
      end
  end

  lane :run_tests do |params|
    # Validate input parameters
    test_type = params[:type] || "Both"

    case test_type.downcase
    when "Both"
      puts "🚀 Running Both Unit and UI Tests"
      unit_tests
      ui_tests
    when "UI Test"
      puts "🖥️ Running UI Tests Only"
      ui_tests
    when "Unit Test"
      puts "🧪 Running Unit Tests Only"
      unit_tests
    else
      UI.user_error!("Invalid test type. Use 'Both', 'UI', or 'Unit'")
    end
  end

  desc "Run unit tests"
    lane :unit_tests do
      ENV['TERM'] = 'dumb'
        gradle(
        task: "test",
        print_command: false,
        properties: {
          "color" => "always"
        }
        )
    end

  desc "Run UI tests"
  lane :ui_tests do
    build_apk

    result_output = ""

    begin
      result_output = gradle(
        task: "connectedAndroidTest",
        print_command: true,
        flags: "--info"
      )
    rescue => e
      UI.message("Gradle command failed while running tests.")
      result_output = e.message
    end

    puts "Filtered Test Results:\n\n"
    failed_tests = 0

    result_output.each_line do |line|
      if line.match(/(SUCCESS|FAILED)/)
        puts line.strip
      end

      if line.match(/FAILED/)
        failed_tests += 1
      end
    end

    summary = result_output.match(/Total tests (\d+), failure (\d+), passed (\d+)/)
    if summary
      total_tests = summary[1]
      failed_tests = summary[2].to_i
      passed_tests = summary[3]

      border_line = "+-----------------------+"
      puts "\n#{border_line}"
      puts "|     Test Results      |"
      puts "#{border_line}"
      puts "| Number of tests:    #{total_tests.ljust(3)} |"
      puts "| Number of success:  #{passed_tests.ljust(3)} |"
      puts "| Number of failures: #{failed_tests.to_s.ljust(3)} |"
      puts "#{border_line}\n"
    else
      puts "No test summary found in the output."
    end

    if failed_tests > 0
      raise "UI Tests failed: #{failed_tests} test(s) did not pass."
    end
  end
end